#Build
FROM golang:1.22.0-alpine
RUN apk add --no-cache gcc musl-dev
WORKDIR /
COPY db /db
WORKDIR /app
#download all dependencies
#Copy DB doesn't work?
COPY go/go.mod go/go.sum ./
COPY go/app ./
RUN go mod tidy

RUN go build -o main ./*.go
RUN addgroup -S mercari && adduser -S trainee -G mercari
RUN chown -R trainee:mercari /db
USER trainee
EXPOSE 9000
CMD ["./main"]
