FROM golang:1.17-alpine

PORT 8080
ENV GOPATH /go
ENV GO111MODULE on

RUN apk update && \
    apk --no-cache add git && \
    apk add --no-cache sqlite && \
    apk add gcc musl-dev gcompat

RUN mkdir /go/src/db
RUN mkdir /go/src/go
WORKDIR /go/src/go

ADD db /go/src/db
ADD go /go/src/go

RUN go mod tidy

WORKDIR /go/src/go/app

CMD ["go run main.go"]