# docker build -t build2022/web .       
# docker run -d -p 3000:3000 build2022/web:latest 

FROM node:18-alpine

WORKDIR /code

COPY package*.json ./

RUN npm ci

COPY . .

ENV PORT=3000

EXPOSE 3000

CMD ["npm", "start"]