FROM FROM python:3.9-slim

WORKDIR /python

RUN addgroup -S mercari && adduser -S trainee -G mercari
RUN python -m venv .venv
RUN source .venv/bin/activate
RUN pip install -r requirements.txt

EXPOSE 9006

USER trainee

CMD ["python", "-V"]
