FROM python:3.11.7

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN groupadd -r mercari && useradd -r -g mercari trainee
# RUN chown -R trainee:mercari /path/to/db

RUN chown -R trainee:mercari /app

USER trainee

EXPOSE 9000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000"]
