FROM python:3.8-slim-buster

WORKDIR /workspace

COPY . /workspace/python

RUN cd python && pip3 install -r requirements.txt

RUN apt update && apt upgrade && apt install -y curl

WORKDIR /workspace/python

CMD ["uvicorn", "main:app", "--reload", "--port", "9000"]
