name: Deploy

on: 
  push:
    branches:
      - main

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    environment:
      name: Production
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: projects/381045458779/locations/global/workloadIdentityPools/mercari-listing/providers/gha-provider
          service_account: github-actions@build-mercari-2022-team6.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build a docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} . -f ./go/dockerfile.production

      - name: Push the docker image to Container Registry
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
            gcloud run deploy mercari-build-2022-backend \
              --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} \
              --project ${{ secrets.GCP_PROJECT_ID }} \
              --region ${{ secrets.GCP_REGION }} \
              --platform=managed \
              --allow-unauthenticated \
              --quiet
